kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-default
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - psp-restrictive
  verbs:
  - use
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-privileged
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - psp-privileged
  verbs:
  - use